# Generated by Django 5.1.5 on 2025-02-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_rename_categories_category_author_alter_task_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, default='fallback_avatar.webp', upload_to='photos'),
        ),
    ]
